sudo: false
language: node_js

notifications:
  email: false

node_js:
  - '8'
  - '6'
  - '4'

before_install:
  - npm install --global npm@latest

before_script:
  - npm prune

after_success:
  - npm run semantic-release
  - bash <(curl -s https://codecov.io/bash)

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
